import Images from '../assets/images'
export default plants = [
    {
      name: "Apple",
      image:Images.apple,
      planting: "Spring planting is recommended in central and northern areas. Fall planting can also be successful but only in areas where autumn and winter weather is generally more mild and moist.As a general rule, if a tree is termed hardy, it grows best in Hardiness Zones 3 to 5. If termed long-season, apple quality will be best in Zones 5 to 8. Check your zone here.Each variety has a number of chill hours needed to set fruit (i.e., the amount of time temperatures are between 32 and 45 degrees F). The farther north you go, the more chill hours an apple variety needs to avoid late spring freeze problems. Check tree tags for chill hour information or ask the seller.Apple trees need well-drained soil, nothing too wet. Soil needs to be moderately rich and retain moisture as well as air; mulch with straw, hay, or some other organic material to keep soil moist and provide nutrients as they decompose. Choose a sunny site. For best fruiting, an apple tree needs “full sunlight,” which means six or more hours of direct summer sun daily. The best exposure for apples is a north- or east-facing slope.",
      care:"Water young trees regularly, especially those on semidwarfing or dwarfing rootstocks, to ensure that the root system becomes well established.Renew mulch periodically, but pull it away from the tree in the fall so mice don’t nest over the winter and eat the bark.",
      pest_diseases:"Apples are prone to insect and diseases—including apple maggots, plum curculios, green fruitworms, and codling moths. Many gardeners who swear off pesticides find they need to find, at minimum, an acceptual annual spray treatment for a decent crop.One idea to avoid pesticides is to select disease-resistant varieties such as ‘Prima’, ‘Priscilla’, ‘Liberty’, and ‘Freedom’. They do not require spraying for apple scab, cedar-apple rust, and other common diseases, while most other varieties require periodic spraying every spring and summer after planting. Check with your extension service to find approved pest prevention programs for your area.You can also try an anti-insect oil, found at garden stores. Spray it in the spring when your apple trees are in the tight cluster stage: after the leaves have unfolded from the fruiting cluster, but before the buds begin to show pink.Other pests such as scales, mites, and aphids should be controlled by natural parasite and predator populations if you haven’t used a lot of sprays. ",
      harves:"Pluck your apples when their background color is no longer green.The stem should part readily from the branch when the fruit is cupped in the palm of your hand and given a slight twist around, then up (do not yank on the apple).Different apple varieties mature at different times, so the harvest season can stretch from August to October.If the apple is overripe and soft, use for cooking!",
      group:3
    },
    {
      name: "Grape",
      image:Images.grape,
      planting: "Plant dormant, bare-root grape vines in the early spring.Construct a trellis or arbor before planting. Grape vines will need to be trained to some sort of support to grow upward. This will also cut the risk of disease.Most grape varieties are self-fertile. To be sure, ask when you are buying vines if you will need more than one plant for pollination.Before planting grapevines, soak their roots in water for two or three hours.Select a site with full sun. If you don’t have a spot with full sun, make sure it at least gets morning sun. A small amount of afternoon shade won’t hurt. Your soil needs to be deep, well-drained, and loose. You also need good air circulation.Space vines 6 to 10 feet apart (16 feet for muscadines).For each vine, dig a planting hole 12 inches deep and 12 inches wide. Fill with 4 inches of topsoil. Trim off broken roots and set the vine into the hole slightly deeper than it grew in the nursery. Cover the roots with 6 inches of soil and tamp down. Fill with the remaining soil, but don’t tamp this down.Prune the top back to two or three buds at planting time.Water at time of planting.",
      care:"In the first couple of years, the vine should not be allowed to produce fruit. It needs to strengthen its root system before it can support the extra weight of fruit.Pruning is important. Not only would vines run rampant without control, but canes will only produce fruit once. Prune annually when vines are dormant, in March or April. This is before the buds start to swell, but when winter damage is apparent.Don’t be afraid to remove at least 90 percent of the previous season’s growth. This will ensure a higher quality product. Remember, the more you prune, the more grapes you will have.In the first year, cut back all buds except for 2 or 3. Then, select a couple of strong canes and cut back the rest. Make sure the remaining canes are fastened to the support.In the second year, prune back all canes. Leave a couple of buds on each of the arms. Remove flower clusters as they form.Do not fertilize in the first year unless you have problem soil. Fertilize lightly in the second year of growth.Use mulch to keep an even amount of moisture around the vines.A mesh net is useful in keeping birds away from budding fruit.",pest_diseases:"sdsp",
      pest_diseases:"Aphids Japanese Beetles/nPowdery Mildew /nBlack Rot",
      harves:"If grapes aren’t ripening, pinch back some of the foliage to let in more sunlight.Grapes will not continue ripening once picked from the vine. Test a few to see if they are to your liking before harvesting, usually in late summer or early fall.Grapes are ripe and ready to harvest when they are rich in color, juicy, full-flavored, easily crushed but not shriveled, and plump. They should be tightly attached to the stems. Sample different grapes from different clusters, and the taste should be between sweet and tart. Check our ripeness guide for more tips on color.Grapes can be stored for up to six weeks in the cellar, but grapes can absorb the odors of other fruits and vegetables, so keep them separate. Use cardboard boxes or crates lined with clean, dry straw. Separate bunches with straw or sawdust. Check often for spoilage.",
      group:4
    },
    {
      name: "Peach",
      image:Images.peach,
      planting: "Before planting peaches, choose a site with well-drained, moderately fertile soil in full sun. Be sure to avoid low areas because frost can more easily settle there and destroy your peaches.Plant the trees in spring. It is best to plant the trees the day you get them (if possible). Pick a tree that is about 1 year old.For container-grown trees, remove the plant from its pot and remove any circling roots by laying the root ball on its side and using shears to cut through the roots.For grafted trees, position the inside of the curve of the graft union away from the sun when planting.Dig a hole that is a few inches deeper and wider than the spread of the roots. Set the tree on top of a small mound of soil in the middle of the hole. Be sure to spread the roots away from the trunk without excessively bending them.If you are planting standard-size trees, space them 15 to 20 feet apart. Space dwarf trees 10 to 12 feet apart. However, most types of peach trees are self-fertile, so planting one tree at a time is fine.",
      care:"Thin the fruits so that they are 6 to 8 inches apart on the branch after the tree blooms (about 4 to 6 weeks). This ensures that the fruits will be larger.Prune and fertilize to accomplish 10 to 18 inches of new growth each season.",pest_diseases:"sdsp",
      pest_diseases:"Borers Aphids Japanese beetles Leaf hoppers Brown rot Powdery mildew Leaf curl Mosaic viruses",
      harves:"Peaches are harvested when they are fully ripe from late June through July and August.With peaches, it’s especially important to harvest at the RIGHT time.Though this timing depends on what type of peach variety, you can generally go by the color of the fruit. When peaches are fully ripe, the ground color of the fruit changes from green to completely yellow. No green should be left on the fruit. They should come off the tree with only a slight twist. The fruits found on the top and outside of the tree usually ripen first.Be careful when picking your peaches because some varieties bruise very easily.",

      group:2
    },
    {
      name: "Potato",
      image:Images.potato,
      planting: "Potatoes can be started 0 to 2 weeks after last spring frost. You may plant earlier, as soon as soil can be worked, but be aware that some crops may be ruined by a frost or wet soil. Find your local frost dates here. However, if have a “late” spring, it’s not too late to plant potatoes through April (depending on where you’re located).  Some folks even plant through June, especially in containers or potato towers.",
      care:"Do not allow sunlight to fall on the tubers, which develop under the surface of the soil, or they will turn green.Do the hilling in the morning, when plants are at their tallest. During the heat of the day, plants start drooping.Maintain even moisture, especially from the time when sprouts appear until several weeks after they blossom. The plants need 1 to 2 inches of water per week. If you water too much right after planting and not enough as the potatoes begin to form, the tubers can become misshapen.The last hilling should be done before the potato plants bloom, when the plant is about 6 inches tall. Hoe the dirt up around the base of the plant in order to cover the tubers as well as to support the plant.Hilling keeps the potatoes from getting sunburned, which can cause them to turn green and produce a chemical called solanine. Solanine gives off a bitter taste and is toxic.",pest_diseases:"sdsp",harves:"sad",
      pest_diseases:"Potato Scab: Most likely caused by a high soil pH. Remember: Potatoes like acidic soil (do not plant in soil with a pH higher than 5.2). Dust seed potatoes with sulfur before planting. Some readers suggest adding pine straw on top of the potatoes when planting for natural anti-bacterial elements.Colorado potato beetles need to be hand-picked and predatory birds will often eat them. While they’re in the nymph state, they can be controlled with Diatomaceous Earth (food grade) which is a non-toxic way to control pests in the garden. If they continue to be a problem, a few sprays of Spinosad, an organic pesticide, will get rid of the beetles. Always use products at dawn or dusk to avoid harming beneficial insects.AphidsFlea BeetlesEarly/Late Bl",
      harves:"“New potatoes,” which are potatoes that are purposefully harvested early for their smaller size and tender skin, will be ready for harvest 2 to 3 weeks after the plants stop flowering. For mature potatoes, wait 2 to 3 weeks after the foliage has died.New potatoes should not be cured and should be eaten within a few days of harvest, as they will not keep for much longer.Dig potatoes on a dry day. Dig up gently, being careful not to puncture the tubers. Avoid cutting or bruising potato skin. The soil should not be compact, so digging should be easy.If the soil is very wet, let the potatoes air-dry as much as possible before putting them in bags or baskets.For the biggest and best potatoes, harvest only after the plant’s foliage has died back.Cut browning foliage to the ground and wait 10 to 14 days before harvesting to allow the potatoes to develop a thick enough skin. Don’t wait too long, though, or the potatoes may rot.Allow freshly dug potatoes to sit in a dry, cool place (45–60°F/7–15°C) for up to two weeks. This allows their skins to cure, which will help them keep for longer.After curing, make sure you brush off any soil clinging to the potatoes, then store them in a cool, somewhat humid, dark place. The ideal temperature for storage is 38 to 40°F (3 to 4°C).Do not store potatoes with apples; the apples’ ethylene gas will cause potatoes to spoil.Never store potatoes in the refrigerator.Whether you dig your own potatoes or buy them at a store, don’t wash them until right before you use them. Washing potatoes shortens their storage l"
    ,
  group:1},
    {
      name: "Tomato",
      image:Images.tomato,
      planting: "If you’re starting tomatoes from seed (versus transplants), you’ll want to start your seeds indoors 6 to 8 weeks before the average last spring frost date. See our Planting Calendar for seed-starting dates specific to your area and our article on “Tomatoes From Seed the Easy Way” for more tips.\n Transplant seedlings after the last spring frost when the soil has warmed. See our Planting Calendar for suggested transplanting dates.\n SELECTING AND PREPARING A PLANTING SITE\n Select a site with full sun and well-drained soil. For northern regions, it is VERY important that your site receives at least 6 hours of daily sunlight. For southern regions, light afternoon shade will help tomatoes survive and thrive.\n Two weeks before transplanting tomato plants outdoors, dig soil to about 1 foot deep and mix in aged manure or compost. Learn more about preparing soil for planting.\n Some sort of support system is recommended, but sprawling plants can also produce fine crops if you have the space and if the weather cooperates. \n HOW TO PLANT TOMATOES\n Harden off seedlings or transplants for a week before planting in the garden. Set young plants outdoors in the shade for a couple of hours the first day, gradually increasing the amount of time the plants are outside each day to include some direct sunlight. Learn more about hardening off seedlings.\n Plant transplants about 2 feet apart.\n Place tomato stakes or cages in the soil at the time of planting to avoid damaging roots later on. Staking keeps developing tomato fruit off the ground, while caging lets the plant hold itself upright. Learn how to build stakes and other tomato supports.\n Pinch off a few of the lower branches on transplants, and plant the root ball deep enough so that the remaining lowest leaves are just above the surface of the soil.\n If your transplants are leggy, you can remedy this by burying up to ⅔ of the plant, including the lower sets of leaves. Tomato stems have the ability to grow roots from the buried stems.\n Water well to reduce shock to the roots.\n GROWING TOMATOES IN CONTAINERS\n Use a large pot or container with drainage holes in the bottom.\n Use loose, well-draining soil. We recommend a good potting mix with added organic matter.\n Plant one tomato plant per pot. Choose from bush or dwarf varieties; many cherry tomatoes grow well in pots. \n Taller varieties may need to be staked.\n Place the pot in a sunny spot with 6 to 8 hours of full sun a day.\n Keep soil moist. Containers will dry out more quickly than the garden soil, so check daily and provide extra water during a heat wave",
      care:"Water generously the first few days.\n Water well throughout the growing season, about 2 inches per week during the summer. Water deeply for a strong root system.\n Water in the early morning. This gives plant the moisture it needs to make it through a hot day. Avoid watering late afternoon or evening. \n Mulch five weeks after transplanting to retain moisture and to control weeds. Mulch also keeps soil from splashing the lower tomato leaves. \n To help tomatoes through periods of drought, find some flat rocks and place one next to each plant. The rocks prevent water from evaporating from the soil.\n Side dress plants with fertilizer or compost every two weeks starting when the tomato fruits are about 1 inch in diameter.\n If using stakes, prune plants by pinching off suckers (side stems) so that only a couple of branches are growing from each plant. The suckers grow between the branch and the main stem.",
      pest_diseases:"Tomatoes are susceptible to insect pests, especially tomato hornworms and whiteflies. Link to our pest & problem pages below.\n Aphid\n Flea Beetle\n Tomato Hornwor\n Whiteflie\n Blossom-End Ro\n Late Blight is a fungal disease that can strike during any part of the growing season. It will cause grey, moldy spots on leaves and fruit which later turn brown. The disease is spread and supported by persistent damp weather. This disease will overwinter, so all infected plants should be destroyed. See our blog on “Avoid Blight With the Right Tomato.\n Mosaic Virus creates distorted leaves and causes young growth to be narrow and twisted, and the leaves become mottled with yellow. Unfortunately, infected plants should be destroyed (but don’t put them in your compost pile)\n Cracking: When fruit growth is too rapid, the skin will crack. This usually occurs due to uneven watering or uneven moisture from weather conditions (very rainy periods mixed with dry periods). Keep moisture levels constant with consistent watering and mulching.",
      harves:"Leave your tomatoes on the vine as long as possible. If any fall off before they appear ripe, place them in a paper bag with the stem up and store them in a cool, dark place.\n Never place tomatoes on a sunny windowsill to ripen; they may rot before they are ripe!\n The perfect tomato for picking will be firm and very red in color, regardless of size, with perhaps some yellow remaining around the stem. If you grow orange, yellow or any other color tomato, wait for the tomato to turn the correct color.\n If your tomato plant still has fruit when the first hard frost threatens, pull up the entire plant and hang it upside down in the basement or garage. Pick tomatoes as they ripen.\n If temperatures start to drop and your tomatoes aren’t ripening, watch this video for tips.\n Never refrigerate fresh tomatoes. Doing so spoils the flavor and texture that make up that garden tomato taste.\n To freeze, core fresh unblemished tomatoes and place them whole in freezer bags or containers. Seal, label, and freeze. The skins will slip off when they defr\n ",
      group:2
    },
    {
      name: "Corn",
      image:Images.corn,
      planting: "Corn plants are picky about their soil. Work in aged manure or compost the fall before planting and let it overwinter in the soil.\nStarting corn seeds indoors is not recommended.\nPlant seeds outdoors two weeks after the last spring frost date.\nMake sure the soil temperature is above 60°F (16°C) for successful germination. (Up to 65°F/18°C for super sweet varieties.) In colder zones, the ground can be warmed by a black plastic cover if necessary. Plant seeds through holes in the plastic.\nPlant seeds 1.5 to 2 inches deep and 4 to 6 inches apart. Rows 30 to 36 inches apart.\nFor sufficient pollination, plan your plot right. Don’t plant two long rows, rather, plant corn blocks of at least four rows.\nYou may choose to fertilize at planting time; corn is meant to grow rapidly. If you are confident that the soil is adequate, this can be skipped.\nWater well at planting time.",
      care:"When your plants are 3 to 4 inches tall, thin them so they are 8 to 12 inches apart.\nBe careful not to damage the roots when weeding.\nSoil must be well drained and able to keep consistent moisture.\nIn dry conditions, be sure to keep corn well watered due to its shallow roots. Water at a rate of 5 gallons per sq yard. Mulch helps reduce evaporation.",
      pest_diseases:"Raccoons \nDeer\nSpotted Cucumber Beetles\nFlea Beetles\nCutworms ",
      harves:"Harvest when tassels begin to turn brown and cobs start to swell. Kernels should be full and milky.\nPull ears downward and twist to take off stalk.\nSweet corn varieties lose their sweetness soon after harvesting.\nPrepare for eating or preserving immediately after picking.\nSweet corn freezes well, especially if removed from ears before freezing. Learn how to properly freeze corn.\nCorn kernels can also be harvested for other purposes, like corn-filled therapy packs.",
      group:3
  
    },
    {
      name: "Strawberry",
      image:Images.strawberry,
      planting: "Strawberry plants require 6-10 hours a day of direct sunlight, so choose your planting site accordingly.\nStrawberries are tolerant of different soil types, although they prefer loam. Ideally, begin working in aged manure or compost a couple months before planting.\nSoil pH should be between 5.5 and 7. If necessary, amend your soil in advance of planting.\nThe planting site must be well-drained. Raised beds are a particularly good option for strawberry plants.\nPractice crop rotation for the most success. Do not plant in a site that recently had strawberries, tomatoes, peppers, or eggplant.\nStrawberries are sprawling plants. Seedlings will send out runners, or ‘daughter’ plants, which in turn will send out their own runners.\nMake planting holes deep and wide enough to accommodate the entire root system without bending it. However, don’t plant too deep: The roots should be covered, but the crown should be right at the soil surface.",
      care:"In the first year, pick off blossoms to discourage strawberry plants from fruiting. If not allowed to bear fruit, they will spend their food reserves on developing healthy roots. The yields will be much greater in the second year.\nEliminate daughter plants as needed. First and second generations produce higher yields. Try to keep daughter plants spaced about 10 inches apart.\nMoisture is incredibly important due to shallow roots. Water adequately, about one inch per week. Strawberry plants need a lot of water when the runners and flowers are developing and again in the fall when the plants are mature.\nKeep the beds mulched to reduce water needs and weed invasion.\nBe diligent about weeding. Weed by hand, especially in the first months after planting.\nWhen the growing season is over, mow or cut foliage down to one inch and mulch plants about 4 inches deep with straw, pine needles or other organic material. This can be done after the first couple of frosts, or when air temps reach 20°F (-6°C).\nRemove mulch in early spring, after danger of frost has passed.\nRow covers are a good option for protecting blossoms and fruit from birds.",
      pest_diseases:"Gray Mold\nPowdery Mildew\nJapanese Beetles\nSpider Mites\nSlugs",
      harves:"Fruit is ready for harvesting 4–6 weeks after blossoming.\nHarvest only fully red (ripe) berries, and pick every three days.\nCut by the stem; do not pull the berry or you could damage the plant.\nFor Junebearer strawberries, the harvest will last up to 3 weeks. You should have an abundance of berries, depending on the variety.\nStore unwashed berries in the refrigerator for 3–5 days.\nStrawberries can be frozen whole for about 2 months.",
      group:1
    },
    {
      name: "Pepper",
      image:Images.apple,
      planting: "Spring planting is recommended in central and northern areas. Fall planting can also be successful but only in areas where autumn and winter weather is generally more mild and moist.As a general rule, if a tree is termed hardy, it grows best in Hardiness Zones 3 to 5. If termed long-season, apple quality will be best in Zones 5 to 8. Check your zone here.Each variety has a number of chill hours needed to set fruit (i.e., the amount of time temperatures are between 32 and 45 degrees F). The farther north you go, the more chill hours an apple variety needs to avoid late spring freeze problems. Check tree tags for chill hour information or ask the seller.Apple trees need well-drained soil, nothing too wet. Soil needs to be moderately rich and retain moisture as well as air; mulch with straw, hay, or some other organic material to keep soil moist and provide nutrients as they decompose. Choose a sunny site. For best fruiting, an apple tree needs “full sunlight,” which means six or more hours of direct summer sun daily. The best exposure for apples is a north- or east-facing slope.",
      care:"Water young trees regularly, especially those on semidwarfing or dwarfing rootstocks, to ensure that the root system becomes well established.Renew mulch periodically, but pull it away from the tree in the fall so mice don’t nest over the winter and eat the bark.",
      pest_diseases:"Apples are prone to insect and diseases—including apple maggots, plum curculios, green fruitworms, and codling moths. Many gardeners who swear off pesticides find they need to find, at minimum, an acceptual annual spray treatment for a decent crop.One idea to avoid pesticides is to select disease-resistant varieties such as ‘Prima’, ‘Priscilla’, ‘Liberty’, and ‘Freedom’. They do not require spraying for apple scab, cedar-apple rust, and other common diseases, while most other varieties require periodic spraying every spring and summer after planting. Check with your extension service to find approved pest prevention programs for your area.You can also try an anti-insect oil, found at garden stores. Spray it in the spring when your apple trees are in the tight cluster stage: after the leaves have unfolded from the fruiting cluster, but before the buds begin to show pink.Other pests such as scales, mites, and aphids should be controlled by natural parasite and predator populations if you haven’t used a lot of sprays. ",
      harves:"Pluck your apples when their background color is no longer green.The stem should part readily from the branch when the fruit is cupped in the palm of your hand and given a slight twist around, then up (do not yank on the apple).Different apple varieties mature at different times, so the harvest season can stretch from August to October.If the apple is overripe and soft, use for cooking!",
      group:3
    },
    {
      name: "Melon",
      image:Images.apple,
      planting: "Spring planting is recommended in central and northern areas. Fall planting can also be successful but only in areas where autumn and winter weather is generally more mild and moist.As a general rule, if a tree is termed hardy, it grows best in Hardiness Zones 3 to 5. If termed long-season, apple quality will be best in Zones 5 to 8. Check your zone here.Each variety has a number of chill hours needed to set fruit (i.e., the amount of time temperatures are between 32 and 45 degrees F). The farther north you go, the more chill hours an apple variety needs to avoid late spring freeze problems. Check tree tags for chill hour information or ask the seller.Apple trees need well-drained soil, nothing too wet. Soil needs to be moderately rich and retain moisture as well as air; mulch with straw, hay, or some other organic material to keep soil moist and provide nutrients as they decompose. Choose a sunny site. For best fruiting, an apple tree needs “full sunlight,” which means six or more hours of direct summer sun daily. The best exposure for apples is a north- or east-facing slope.",
      care:"Water young trees regularly, especially those on semidwarfing or dwarfing rootstocks, to ensure that the root system becomes well established.Renew mulch periodically, but pull it away from the tree in the fall so mice don’t nest over the winter and eat the bark.",
      pest_diseases:"Apples are prone to insect and diseases—including apple maggots, plum curculios, green fruitworms, and codling moths. Many gardeners who swear off pesticides find they need to find, at minimum, an acceptual annual spray treatment for a decent crop.One idea to avoid pesticides is to select disease-resistant varieties such as ‘Prima’, ‘Priscilla’, ‘Liberty’, and ‘Freedom’. They do not require spraying for apple scab, cedar-apple rust, and other common diseases, while most other varieties require periodic spraying every spring and summer after planting. Check with your extension service to find approved pest prevention programs for your area.You can also try an anti-insect oil, found at garden stores. Spray it in the spring when your apple trees are in the tight cluster stage: after the leaves have unfolded from the fruiting cluster, but before the buds begin to show pink.Other pests such as scales, mites, and aphids should be controlled by natural parasite and predator populations if you haven’t used a lot of sprays. ",
      harves:"Pluck your apples when their background color is no longer green.The stem should part readily from the branch when the fruit is cupped in the palm of your hand and given a slight twist around, then up (do not yank on the apple).Different apple varieties mature at different times, so the harvest season can stretch from August to October.If the apple is overripe and soft, use for cooking!",
      group:3
      
    },
    {
    name: "Onion",
    image:Images.potato,
    planting: "Spring planting is recommended in central and northern areas. Fall planting can also be successful but only in areas where autumn and winter weather is generally more mild and moist.As a general rule, if a tree is termed hardy, it grows best in Hardiness Zones 3 to 5. If termed long-season, apple quality will be best in Zones 5 to 8. Check your zone here.Each variety has a number of chill hours needed to set fruit (i.e., the amount of time temperatures are between 32 and 45 degrees F). The farther north you go, the more chill hours an apple variety needs to avoid late spring freeze problems. Check tree tags for chill hour information or ask the seller.Apple trees need well-drained soil, nothing too wet. Soil needs to be moderately rich and retain moisture as well as air; mulch with straw, hay, or some other organic material to keep soil moist and provide nutrients as they decompose. Choose a sunny site. For best fruiting, an apple tree needs “full sunlight,” which means six or more hours of direct summer sun daily. The best exposure for apples is a north- or east-facing slope.",
      care:"Water young trees regularly, especially those on semidwarfing or dwarfing rootstocks, to ensure that the root system becomes well established.Renew mulch periodically, but pull it away from the tree in the fall so mice don’t nest over the winter and eat the bark.",
      pest_diseases:"Apples are prone to insect and diseases—including apple maggots, plum curculios, green fruitworms, and codling moths. Many gardeners who swear off pesticides find they need to find, at minimum, an acceptual annual spray treatment for a decent crop.One idea to avoid pesticides is to select disease-resistant varieties such as ‘Prima’, ‘Priscilla’, ‘Liberty’, and ‘Freedom’. They do not require spraying for apple scab, cedar-apple rust, and other common diseases, while most other varieties require periodic spraying every spring and summer after planting. Check with your extension service to find approved pest prevention programs for your area.You can also try an anti-insect oil, found at garden stores. Spray it in the spring when your apple trees are in the tight cluster stage: after the leaves have unfolded from the fruiting cluster, but before the buds begin to show pink.Other pests such as scales, mites, and aphids should be controlled by natural parasite and predator populations if you haven’t used a lot of sprays. ",
      harves:"Pluck your apples when their background color is no longer green.The stem should part readily from the branch when the fruit is cupped in the palm of your hand and given a slight twist around, then up (do not yank on the apple).Different apple varieties mature at different times, so the harvest season can stretch from August to October.If the apple is overripe and soft, use for cooking!",
      group:3
  },
  {
    name: "Orange",
    image:Images.peach,
    planting: "Spring planting is recommended in central and northern areas. Fall planting can also be successful but only in areas where autumn and winter weather is generally more mild and moist.As a general rule, if a tree is termed hardy, it grows best in Hardiness Zones 3 to 5. If termed long-season, apple quality will be best in Zones 5 to 8. Check your zone here.Each variety has a number of chill hours needed to set fruit (i.e., the amount of time temperatures are between 32 and 45 degrees F). The farther north you go, the more chill hours an apple variety needs to avoid late spring freeze problems. Check tree tags for chill hour information or ask the seller.Apple trees need well-drained soil, nothing too wet. Soil needs to be moderately rich and retain moisture as well as air; mulch with straw, hay, or some other organic material to keep soil moist and provide nutrients as they decompose. Choose a sunny site. For best fruiting, an apple tree needs “full sunlight,” which means six or more hours of direct summer sun daily. The best exposure for apples is a north- or east-facing slope.",
      care:"Water young trees regularly, especially those on semidwarfing or dwarfing rootstocks, to ensure that the root system becomes well established.Renew mulch periodically, but pull it away from the tree in the fall so mice don’t nest over the winter and eat the bark.",
      pest_diseases:"Apples are prone to insect and diseases—including apple maggots, plum curculios, green fruitworms, and codling moths. Many gardeners who swear off pesticides find they need to find, at minimum, an acceptual annual spray treatment for a decent crop.One idea to avoid pesticides is to select disease-resistant varieties such as ‘Prima’, ‘Priscilla’, ‘Liberty’, and ‘Freedom’. They do not require spraying for apple scab, cedar-apple rust, and other common diseases, while most other varieties require periodic spraying every spring and summer after planting. Check with your extension service to find approved pest prevention programs for your area.You can also try an anti-insect oil, found at garden stores. Spray it in the spring when your apple trees are in the tight cluster stage: after the leaves have unfolded from the fruiting cluster, but before the buds begin to show pink.Other pests such as scales, mites, and aphids should be controlled by natural parasite and predator populations if you haven’t used a lot of sprays. ",
      harves:"Pluck your apples when their background color is no longer green.The stem should part readily from the branch when the fruit is cupped in the palm of your hand and given a slight twist around, then up (do not yank on the apple).Different apple varieties mature at different times, so the harvest season can stretch from August to October.If the apple is overripe and soft, use for cooking!",
      group:3
  },
  {
    name: "Mango",
    image:Images.apple,
    planting: "Spring planting is recommended in central and northern areas. Fall planting can also be successful but only in areas where autumn and winter weather is generally more mild and moist.As a general rule, if a tree is termed hardy, it grows best in Hardiness Zones 3 to 5. If termed long-season, apple quality will be best in Zones 5 to 8. Check your zone here.Each variety has a number of chill hours needed to set fruit (i.e., the amount of time temperatures are between 32 and 45 degrees F). The farther north you go, the more chill hours an apple variety needs to avoid late spring freeze problems. Check tree tags for chill hour information or ask the seller.Apple trees need well-drained soil, nothing too wet. Soil needs to be moderately rich and retain moisture as well as air; mulch with straw, hay, or some other organic material to keep soil moist and provide nutrients as they decompose. Choose a sunny site. For best fruiting, an apple tree needs “full sunlight,” which means six or more hours of direct summer sun daily. The best exposure for apples is a north- or east-facing slope.",
      care:"Water young trees regularly, especially those on semidwarfing or dwarfing rootstocks, to ensure that the root system becomes well established.Renew mulch periodically, but pull it away from the tree in the fall so mice don’t nest over the winter and eat the bark.",
      pest_diseases:"Apples are prone to insect and diseases—including apple maggots, plum curculios, green fruitworms, and codling moths. Many gardeners who swear off pesticides find they need to find, at minimum, an acceptual annual spray treatment for a decent crop.One idea to avoid pesticides is to select disease-resistant varieties such as ‘Prima’, ‘Priscilla’, ‘Liberty’, and ‘Freedom’. They do not require spraying for apple scab, cedar-apple rust, and other common diseases, while most other varieties require periodic spraying every spring and summer after planting. Check with your extension service to find approved pest prevention programs for your area.You can also try an anti-insect oil, found at garden stores. Spray it in the spring when your apple trees are in the tight cluster stage: after the leaves have unfolded from the fruiting cluster, but before the buds begin to show pink.Other pests such as scales, mites, and aphids should be controlled by natural parasite and predator populations if you haven’t used a lot of sprays. ",
      harves:"Pluck your apples when their background color is no longer green.The stem should part readily from the branch when the fruit is cupped in the palm of your hand and given a slight twist around, then up (do not yank on the apple).Different apple varieties mature at different times, so the harvest season can stretch from August to October.If the apple is overripe and soft, use for cooking!",
      group:3
  },
    ]