export default solutions = const solution = {
    1:{ title:"What is This?",
    description:"Corn is a starchy vegetable and cereal grain that has been eaten all over the world for centuries.", 
    imageUrl:require('../../assets/images/advisory_vector.jpeg'),
    comments:[
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons A",
      id:1},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons B",
      id:2},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons C",
      id:3},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons D",
      id:4},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons E",
      id:5}
    ]},
    2:{ title:"What is This?",
    description:"Corn is a starchy vegetable and cereal grain that has been eaten all over the world for centuries.", 
    imageUrl:require('../../assets/images/advisory_vector.jpeg'),
    comments:[
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons A",
      id:1},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons B",
      id:2},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons C",
      id:3},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons D",
      id:4},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons E",
      id:5}
    ]},
    3:{ title:"What is This?",
    description:"Corn is a starchy vegetable and cereal grain that has been eaten all over the world for centuries.", 
    imageUrl:require('../../assets/images/advisory_vector.jpeg'),
    comments:[
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons A",
      id:1},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons B",
      id:2},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons C",
      id:3},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons D",
      id:4},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons E",
      id:5}
    ]},
    4:{ title:"What is This?",
    description:"Corn is a starchy vegetable and cereal grain that has been eaten all over the world for centuries.", 
    imageUrl:require('../../assets/images/advisory_vector.jpeg'),
    comments:[
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons A",
      id:1},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons B",
      id:2},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons C",
      id:3},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons D",
      id:4},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons E",
      id:5}
    ]},
    5:{ title:"What is This?",
    description:"Corn is a starchy vegetable and cereal grain that has been eaten all over the world for centuries.", 
    imageUrl:require('../../assets/images/advisory_vector.jpeg'),
    comments:[
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons A",
      id:1},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons B",
      id:2},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons C",
      id:3},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons D",
      id:4},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons E",
      id:5}
    ]},
    6:{ title:"What is This?",
    description:"Corn is a starchy vegetable and cereal grain that has been eaten all over the world for centuries.", 
    imageUrl:require('../../assets/images/advisory_vector.jpeg'),
    comments:[
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons A",
      id:1},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons B",
      id:2},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons C",
      id:3},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons D",
      id:4},
      {answer:"Here is the full set of answers gonna get from DB",
      name:"Dr. Dragons E",
      id:5}
    ]}
  }
  